name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PRE-DEPLOY - Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: DEPLOY - Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./fluentd
          file: ./fluentd/Dockerfile
          push: true
          tags: nessgis/logs-service:latest
